#[target.x86_64-unknown-freebsd]
#linker = "gcc"
#rustflags = "-L/usr/local/lib"


#[target.x86_64-apple-darwin]
#linker = "x86_64-apple-darwin14-clang"
#ar = "x86_64-apple-darwin14-ar"

#[target.x86_64-pc-windows-gnu]
#rustflags = [
#	"-C", "link-arg=libvcruntime.lib"
#]






