
#name: Mac Rust Build Released

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  # Single deploy job since we're just deploying
  build_mac:
    if: github.repository_owner == 'myridia'
    runs-on: macos-12  
    steps:
      - name: get_repository
        run: |
          brew install rust rustc-completion
   
      - name: checkout repo
        uses: actions/checkout@v4
 
      
      - name: compile macos
        run: |
          cargo build --release 

      - name: list macos binary
        run: |
          ls target/release


      - name: Upload Linux Binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/release/couchy'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true     
