
name: Mac Rust Build Released

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  deploy:
    if: github.repository_owner == 'myridia'
    runs-on: macos-latest   
    steps:
      - name: get_repository
        run: |
          brew install rust rustup-init rustc-completion
   

      
     
