name: Build Rust Released

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  deploy:
    if: github.repository_owner == 'myridia'
    runs-on: ubuntu-latest   
    steps:
      #- name: get_repository
      #  run: |
      #    sudo apt-get install curl build-essential gcc make rustc cargo -y
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: compile
        run: |
          ls 
          # cargo build ../ --target --release 
 
     
