name: Build Rust Released

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  deploy:
    if: github.repository_owner == 'myridia'
    runs-on: ubuntu-latest   
    steps:
      - name: get_repository
        run: |
         sudo apt-get install curl build-essential gcc make mingw-w64 rustc cargo -y
         
      - name: checkout repo
        uses: actions/checkout@v4

      - name: add compile targets
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup target add x86_64-unknown-linux-gnu 
          rustup target add x86_64-apple-darwin 
        
      #- name: compile linux
      #  run: |
      #    cargo build --target x86_64-unknown-linux-gnu --release 

              
      #- name: compile windows
      #  run: |
      #    cargo build --target x86_64-pc-windows-gnu --release 

      - name: compile macos
        run: |
         cargo build --target x86_64-apple-darwin --release 
 
     
