name: Build Rust Released

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  build:
    if: github.repository_owner == 'myridia'
    runs-on: ubuntu-latest   
    steps:
      - name: Install Dependencies
        run: |
         sudo apt-get install curl build-essential gcc make mingw-w64 -y
         sudo apt-get install rustc cargo gzip -y
         sudo apt-get install g++ zlib1g-dev libmpc-dev libmpfr-dev  libgmp-dev
         
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile windows
        run: |
          rustup target add x86_64-pc-windows-gnu
          cargo build --target x86_64-pc-windows-gnu --release 
         

      #- name: compile linux
      #  run: |
      #    cargo build --target --release 
          
      - name: List binary
        run: |
          ls target/x86_64-pc-windows-gnu/release


      - name: Upload binaries to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'target/x86_64-pc-windows-gnu/release/couchy.exe'
          token: ${{ secrets.GITHUB_TOKEN }}

      #- name: compile freebsd
      #  run: |
      #  rustup target add x86_64-unknown-freebsd 
      #   cargo build --target x86_64-unknown-freebsd --release 

        


        


 
     
